version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: clinica
      DB_PASSWORD: 1234
      DB_NAME: clinica
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: clinica
      MYSQL_USER: clinica
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8080:80"

  mobile:
    build: ./mobile
    volumes:
      - ./mobile:/app
      - /app/node_modules
    command: npx expo start --tunnel
    ports:
      - "19000:19000" # Expo bundler
      - "19001:19001" # LAN
      - "19002:19002" # DevTools
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql_data:
