/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CreateAccountScreen` | `/CreateAccountScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Navigation` | `/Navigation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/PreAgendamentoScreen` | `/PreAgendamentoScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SettingsScreen` | `/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/types` | `/types`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/CreateAccountScreen` | `/CreateAccountScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Navigation` | `/Navigation`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/PreAgendamentoScreen` | `/PreAgendamentoScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SettingsScreen` | `/SettingsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/types` | `/types`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/CreateAccountScreen${`?${string}` | `#${string}` | ''}` | `/CreateAccountScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/HomeScreen${`?${string}` | `#${string}` | ''}` | `/HomeScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/LoginScreen${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Navigation${`?${string}` | `#${string}` | ''}` | `/Navigation${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/PreAgendamentoScreen${`?${string}` | `#${string}` | ''}` | `/PreAgendamentoScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SettingsScreen${`?${string}` | `#${string}` | ''}` | `/SettingsScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/types${`?${string}` | `#${string}` | ''}` | `/types${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CreateAccountScreen` | `/CreateAccountScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Navigation` | `/Navigation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/PreAgendamentoScreen` | `/PreAgendamentoScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SettingsScreen` | `/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/types` | `/types`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
